# theme: jekyll-theme-merlot
# theme: jekyll-theme-cayman
# theme: jekyll-theme-slate
# theme: jekyll-theme-tactile
# theme: jekyll-theme-minimal
theme: jekyll-theme-architect
# theme: jekyll-theme-hacker
# theme: jekyll-theme-leap-day
# theme: jekyll-theme-midnight
# theme: minima